# ----
# 작성목적 : 통합 영상 분석 API conda 환경 설정 파일
# 작성일 : 2025-06-18

# 변경사항 내역 (날짜 | 변경목적 | 변경내용 | 작성자 순으로 기입)
# 2025-06-18 | 최초 구현 | conda 환경 자동 구성을 위한 YAML 파일 생성 | 이재인
# 2025-06-24 | 환경 업데이트 | new_pipeline 환경에 맞춰 패키지 목록 동기화 | 이재인
# ----

name: new_pipeline
channels:
  - conda-forge
  - pytorch
  - defaults

dependencies:
  # Python 버전 고정
  - python=3.9.23

  # ============================================================================
  # conda로 설치할 기본 패키지들 (안정성과 호환성 우선)
  # ============================================================================
  
  # 시스템 라이브러리
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - libexpat=2.7.0
  - libffi=3.4.6
  - liblzma=5.8.1
  - libsqlite=3.50.1
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.5.0
  - readline=8.2
  - tk=8.6.13
  
  # 기본 Python 패키지 관리
  - pip=25.1.1
  - setuptools=80.9.0
  - wheel=0.45.1
  
  # ============================================================================
  # pip로 설치할 패키지들 (현재 환경에 설치된 버전과 동일)
  # ============================================================================
  - pip
  - pip:
    # AI/ML 핵심 라이브러리
    - absl-py==2.3.0
    - numpy==1.24.4
    - scipy==1.11.4
    - scikit-learn==1.3.2
    - pandas==2.0.3
    
    # 딥러닝 프레임워크
    - torch==2.7.1
    - torchvision==0.22.1
    - torchaudio==2.7.1
    - jax==0.4.30
    - jaxlib==0.4.30
    
    # 컴퓨터 비전
    - opencv-python==4.8.1.78
    - opencv-contrib-python==4.11.0.86
    - mediapipe==0.10.21
    - ultralytics==8.3.154
    - ultralytics-thop==2.0.14
    - pillow==10.4.0
    
    # 데이터 시각화
    - matplotlib==3.7.5
    - seaborn==0.12.2
    - contourpy==1.3.0
    - cycler==0.12.1
    - fonttools==4.58.4
    - kiwisolver==1.4.7
    - pyparsing==3.2.3
    
    # FastAPI 웹 프레임워크
    - fastapi==0.104.1
    - uvicorn==0.24.0.post1
    - starlette==0.27.0
    - pydantic==2.11.7
    - pydantic-core==2.33.2
    - python-multipart==0.0.20
    
    # HTTP 클라이언트 및 비동기 처리
    - aiofiles==24.1.0
    - aiohttp==3.12.13
    - aiohappyeyeballs==2.6.1
    - aiomysql==0.2.0
    - aiosignal==1.3.2
    - anyio==3.7.1
    - async-timeout==5.0.1
    - attrs==25.3.0
    - h11==0.16.0
    - httpcore==1.0.9
    - httpx==0.28.1
    - requests==2.32.4
    - sniffio==1.3.1
    - frozenlist==1.7.0
    - multidict==6.4.4
    - propcache==0.3.2
    - yarl==1.20.1
    
    # 데이터베이스 드라이버
    - pymongo==4.13.1
    - motor==3.7.1
    - pymysql==1.1.1
    - mysql-connector-python==9.3.0
    - dnspython==2.7.0
    
    # AWS SDK
    - boto3==1.38.36
    - botocore==1.38.36
    - s3transfer==0.13.0
    - jmespath==1.0.1
    
    # OpenAI 및 언어 모델
    - openai==1.86.0
    - openai-whisper==20240930
    - tiktoken==0.9.0
    - transformers==4.52.4
    - tokenizers==0.21.1
    - huggingface-hub==0.33.0
    - safetensors==0.5.3
    - sentencepiece==0.2.0
    
    # 오디오 처리
    - librosa==0.11.0
    - soundfile==0.13.1
    - sounddevice==0.5.2
    - audioread==3.0.1
    - soxr==0.5.0.post1
    - pydub==0.25.1
    - praat-parselmouth==0.4.6
    - speechbrain==1.0.3
    - whisper==1.1.10
    
    # 파일 처리 및 유틸리티
    - openpyxl==3.1.5
    - pypdf==5.6.0
    - python-dotenv==1.1.0
    - dotenv==0.9.9
    - pyyaml==6.0.2
    - ruamel-yaml==0.18.14
    - ruamel-yaml-clib==0.2.12
    - hyperpyyaml==1.2.2
    
    # 데이터 처리
    - datasets==3.6.0
    - pyarrow==20.0.0
    - dill==0.3.8
    - fsspec==2025.3.0
    - multiprocess==0.70.16
    - xxhash==3.5.0
    
    # 수치 계산
    - numba==0.60.0
    - llvmlite==0.43.0
    - ml-dtypes==0.5.1
    - opt-einsum==3.4.0
    - sympy==1.14.0
    - mpmath==1.3.0
    - networkx==3.2.1
    
    # 개발 도구
    - black==25.1.0
    - pytest==8.4.0
    - iniconfig==2.1.0
    - pluggy==1.6.0
    - exceptiongroup==1.3.0
    - tomli==2.2.1
    - mypy-extensions==1.1.0
    - pathspec==0.12.1
    - platformdirs==4.3.8
    - click==8.1.8
    
    # 기타 유틸리티
    - tqdm==4.67.1
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - tzdata==2025.2
    - six==1.17.0
    - packaging==25.0
    - typing-extensions==4.14.0
    - typing-inspection==0.4.1
    - importlib-metadata==8.7.0
    - importlib-resources==6.5.2
    - zipp==3.23.0
    - more-itertools==10.7.0
    - annotated-types==0.7.0
    - jiter==0.10.0
    - certifi==2025.4.26
    - charset-normalizer==3.4.2
    - idna==3.10
    - urllib3==1.26.20
    - distro==1.9.0
    - filelock==3.18.0
    - joblib==1.5.1
    - threadpoolctl==3.6.0
    - regex==2024.11.6
    - decorator==5.2.1
    - lazy-loader==0.4
    - pooch==1.8.2
    - msgpack==1.1.1
    - flatbuffers==25.2.10
    - protobuf==4.25.8
    - jinja2==3.1.6
    - markupsafe==3.0.2
    - pygments==2.19.1
    - cffi==1.17.1
    - pycparser==2.22
    - psutil==7.0.0
    - py-cpuinfo==9.0.0
    - utils==1.0.2
    - et-xmlfile==2.0.0
    - hf-xet==1.1.4

# ============================================================================
# 환경 설정 가이드
# ============================================================================

# 환경 생성 및 설치:
# conda env create -f environment.yml
# conda activate new_pipeline

# 패키지 업데이트:
# conda env update -f environment.yml --prune

# 환경 삭제:
# conda env remove -n new_pipeline 