# ----
# 작성목적 : 통합 영상 분석 API conda 환경 설정 파일
# 작성일 : 2025-06-18

# 변경사항 내역 (날짜 | 변경목적 | 변경내용 | 작성자 순으로 기입)
# 2025-06-18 | 최초 구현 | conda 환경 자동 구성을 위한 YAML 파일 생성 | 이재인
# ----

name: model_video
channels:
  - conda-forge
  - pytorch
  - defaults

dependencies:
  # Python 버전 고정
  - python=3.9.23

  # ============================================================================
  # conda로 설치할 기본 패키지들 (안정성과 호환성 우선)
  # ============================================================================
  
  # 핵심 수치 계산 라이브러리
  - numpy=1.24.4
  - scipy=1.11.4
  - scikit-learn=1.3.2
  
  # 데이터 처리
  - pandas=2.0.3
  
  # 시각화
  - matplotlib=3.7.5
  - seaborn=0.12.2
  
  # 이미지 처리 (conda-forge에서 안정적으로 제공)
  - pillow=10.4.0
  
  # PyTorch 생태계 (pytorch 채널에서 최적화된 버전)
  - pytorch=2.7.1
  - torchvision=0.22.1
  - cpuonly  # CPU 전용 (GPU 필요시 제거하고 cudatoolkit 추가)
  
  # 개발 도구
  - black=25.1.0
  - pytest=8.4.0
  
  # 기본 유틸리티
  - pyyaml=6.0.2
  - click=8.1.8
  - tqdm=4.67.1
  
  # ============================================================================
  # pip로 설치할 패키지들 (conda에서 제공되지 않거나 최신 버전 필요)
  # ============================================================================
  - pip
  - pip:
    # 컴퓨터 비전 (OpenCV는 pip 버전이 더 안정적)
    - opencv-python==4.8.1.78
    - mediapipe==0.10.21
    - ultralytics==8.3.154
    
    # FastAPI 웹 프레임워크
    - fastapi==0.104.1
    - uvicorn==0.24.0.post1
    - pydantic==2.11.7
    - pydantic-core==2.33.2
    - python-multipart==0.0.20
    
    # HTTP 클라이언트 및 비동기 처리
    - requests==2.32.4
    - httpx==0.28.1
    - httpcore==1.0.9
    - aiofiles==24.1.0
    - aiohttp==3.12.13
    - anyio==3.7.1
    - asyncio-timeout==5.0.1
    
    # 데이터베이스 드라이버
    - pymongo==4.13.1
    - motor==3.7.1
    - aiomysql==0.2.0
    - pymysql==1.1.1
    
    # AWS SDK
    - boto3==1.38.36
    - botocore==1.38.36
    
    # OpenAI API
    - openai==1.86.0
    
    # 파일 처리 유틸리티
    - openpyxl==3.1.5
    - python-dotenv==1.1.0
    
    # 기본 유틸리티
    - typing-extensions==4.14.0
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - six==1.17.0

# ============================================================================
# 선택적 구성 (주석 해제하여 사용)
# ============================================================================

# GPU 지원이 필요한 경우 (cpuonly 제거하고 아래 추가):
# - cudatoolkit=11.8  # 또는 사용 중인 CUDA 버전
# - pytorch-cuda=11.8  # PyTorch CUDA 지원

# 개발 환경 추가 도구:
# - jupyter
# - ipython
# - notebook

# 시스템 모니터링:
# - psutil

# 고급 데이터 처리:
# - pyarrow
# - openpyxl 